/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesYandexAdsRouteImport } from './routes/services.yandex-ads'
import { Route as ServicesVideoRouteImport } from './routes/services.video'
import { Route as ServicesUxUiRouteImport } from './routes/services.ux-ui'
import { Route as ServicesTiktokAdsRouteImport } from './routes/services.tiktok-ads'
import { Route as ServicesSmmRouteImport } from './routes/services.smm'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesInstagramAdsRouteImport } from './routes/services.instagram-ads'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services.google-ads'
import { Route as ServicesComplexRouteImport } from './routes/services.complex'
import { Route as ServicesAuditRouteImport } from './routes/services.audit'
import { Route as ServicesAnalyticsRouteImport } from './routes/services.analytics'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesYandexAdsRoute = ServicesYandexAdsRouteImport.update({
  id: '/yandex-ads',
  path: '/yandex-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVideoRoute = ServicesVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesUxUiRoute = ServicesUxUiRouteImport.update({
  id: '/ux-ui',
  path: '/ux-ui',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTiktokAdsRoute = ServicesTiktokAdsRouteImport.update({
  id: '/tiktok-ads',
  path: '/tiktok-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSmmRoute = ServicesSmmRouteImport.update({
  id: '/smm',
  path: '/smm',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInstagramAdsRoute = ServicesInstagramAdsRouteImport.update({
  id: '/instagram-ads',
  path: '/instagram-ads',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/services/google-ads',
  path: '/services/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesComplexRoute = ServicesComplexRouteImport.update({
  id: '/complex',
  path: '/complex',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAuditRoute = ServicesAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAnalyticsRoute = ServicesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/audit': typeof ServicesAuditRoute
  '/services/complex': typeof ServicesComplexRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/instagram-ads': typeof ServicesInstagramAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/smm': typeof ServicesSmmRoute
  '/services/tiktok-ads': typeof ServicesTiktokAdsRoute
  '/services/ux-ui': typeof ServicesUxUiRoute
  '/services/video': typeof ServicesVideoRoute
  '/services/yandex-ads': typeof ServicesYandexAdsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/audit': typeof ServicesAuditRoute
  '/services/complex': typeof ServicesComplexRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/instagram-ads': typeof ServicesInstagramAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/smm': typeof ServicesSmmRoute
  '/services/tiktok-ads': typeof ServicesTiktokAdsRoute
  '/services/ux-ui': typeof ServicesUxUiRoute
  '/services/video': typeof ServicesVideoRoute
  '/services/yandex-ads': typeof ServicesYandexAdsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services/analytics': typeof ServicesAnalyticsRoute
  '/services/audit': typeof ServicesAuditRoute
  '/services/complex': typeof ServicesComplexRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/instagram-ads': typeof ServicesInstagramAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/smm': typeof ServicesSmmRoute
  '/services/tiktok-ads': typeof ServicesTiktokAdsRoute
  '/services/ux-ui': typeof ServicesUxUiRoute
  '/services/video': typeof ServicesVideoRoute
  '/services/yandex-ads': typeof ServicesYandexAdsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/services/analytics'
    | '/services/audit'
    | '/services/complex'
    | '/services/google-ads'
    | '/services/instagram-ads'
    | '/services/seo'
    | '/services/smm'
    | '/services/tiktok-ads'
    | '/services/ux-ui'
    | '/services/video'
    | '/services/yandex-ads'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/services/analytics'
    | '/services/audit'
    | '/services/complex'
    | '/services/google-ads'
    | '/services/instagram-ads'
    | '/services/seo'
    | '/services/smm'
    | '/services/tiktok-ads'
    | '/services/ux-ui'
    | '/services/video'
    | '/services/yandex-ads'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/services/analytics'
    | '/services/audit'
    | '/services/complex'
    | '/services/google-ads'
    | '/services/instagram-ads'
    | '/services/seo'
    | '/services/smm'
    | '/services/tiktok-ads'
    | '/services/ux-ui'
    | '/services/video'
    | '/services/yandex-ads'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/yandex-ads': {
      id: '/services/yandex-ads'
      path: '/yandex-ads'
      fullPath: '/services/yandex-ads'
      preLoaderRoute: typeof ServicesYandexAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/video': {
      id: '/services/video'
      path: '/video'
      fullPath: '/services/video'
      preLoaderRoute: typeof ServicesVideoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ux-ui': {
      id: '/services/ux-ui'
      path: '/ux-ui'
      fullPath: '/services/ux-ui'
      preLoaderRoute: typeof ServicesUxUiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tiktok-ads': {
      id: '/services/tiktok-ads'
      path: '/tiktok-ads'
      fullPath: '/services/tiktok-ads'
      preLoaderRoute: typeof ServicesTiktokAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/smm': {
      id: '/services/smm'
      path: '/smm'
      fullPath: '/services/smm'
      preLoaderRoute: typeof ServicesSmmRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/instagram-ads': {
      id: '/services/instagram-ads'
      path: '/instagram-ads'
      fullPath: '/services/instagram-ads'
      preLoaderRoute: typeof ServicesInstagramAdsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/services/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/complex': {
      id: '/services/complex'
      path: '/complex'
      fullPath: '/services/complex'
      preLoaderRoute: typeof ServicesComplexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/audit': {
      id: '/services/audit'
      path: '/audit'
      fullPath: '/services/audit'
      preLoaderRoute: typeof ServicesAuditRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/analytics': {
      id: '/services/analytics'
      path: '/analytics'
      fullPath: '/services/analytics'
      preLoaderRoute: typeof ServicesAnalyticsRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
